2024-12-13 12:01:18,149 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/vladimirchi/PycharmProjects/pythonProject_2/.venv/Module_12_hw_4.py", line 20, in test_run
    runner_1 = Runner(1000, 10)
               ^^^^^^^^^^^^^^^^
  File "/Users/vladimirchi/PycharmProjects/pythonProject_2/.venv/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-13 12:01:18,150 | INFO | test_run" выполнен успешно
2024-12-13 12:01:18,150 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/vladimirchi/PycharmProjects/pythonProject_2/.venv/Module_12_hw_4.py", line 32, in test_walk
    walker_2 = Runner('Bob', -10)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/vladimirchi/PycharmProjects/pythonProject_2/.venv/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
2024-12-13 12:01:18,150 | INFO | test_walk" выполнен успешно
